[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.17.0"
  NEXT_USE_STANDALONE = "1"
  NEXT_FORCE_EDGE_IMAGES = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    includeFiles = ["public/**/*", ".next/**/*"]
    staticExports = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"